version: '3.7'

services:
  db:
    image: mysql
    container_name: db
    ports:
      - 3306:3306
    env_file:
      - .env
#    volumes:
#      - mysql:/var/lib/mysql/data/
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi_app
    command: bash -c "alembic upgrade head && gunicorn backend.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

#volumes:
#  mysql: